# Original-from: https://gitlab.com/fsci/resources
FROM docker.io/library/debian:sid-slim as builder

ARG packages="build-essential debhelper lintian dh-make vim sudo"
#	      dh-make-golang dh-golang
#  git-buildpackage pbuilder

RUN apt-get update -qq \
	&& apt-get upgrade -y \
        && apt-get install -y -m $packages \
        && rm -rf /var/lib/apt/lists/* \
        && useradd -ms /bin/bash developer \
        && echo "developer:developer" | chpasswd \
        && adduser developer sudo \
	&& echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/015_developer-nopasswd


FROM docker.io/library/debian:sid-slim

USER developer
WORKDIR /home/developer

COPY --from=builder / /
